baseURL = 'https://resephub.netlify.app/'
author = 'Dhifaf Ikhsan Sabil'
languageCode = 'en-us'
title = 'ResepHub 🍽️🍷'
pygmentsUseClasses = true
enableInlineShortcodes = true
googleAnalytics = "G-17PYHEPL5B"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true

[params]
  showDescriptioninHome = true
  titleIcon = 'title'
  [params.headers]
    key = 'Recipes'
    value = 'Description/Tags'

[permalinks]
  tags = "@:slug"

[taxonomies]
  tags = "tags"

[outputs]
  home = [ "HTML", "JSON", "RSS"]

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [twitter]
    disableInlineCSS = true